CREATE TABLE IF NOT EXISTS genres (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	description varchar(200)
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(100) NOT NULL,
	login VARCHAR(100) NOT NULL,
	name VARCHAR(100) NULL,
	birthday DATE,
	CONSTRAINT users_email_unique UNIQUE (email),
	CONSTRAINT users_login_unique UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS films (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(200),
	release_date DATE,
	duration INTEGER,
	rating_id INTEGER,
	CONSTRAINT films_mpa_fk FOREIGN KEY (rating_id) REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS friends (
	user_id INTEGER,
	friend_id INTEGER,
	status BOOLEAN,
	CONSTRAINT friends_pk PRIMARY KEY (user_id, friend_id),
	CONSTRAINT friends_users_user_fk FOREIGN KEY (user_id) REFERENCES users(id),
	CONSTRAINT friends_users_friend_fk FOREIGN KEY (friend_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS likes (
	film_id INTEGER,
	user_id INTEGER,
	CONSTRAINT likes_pk PRIMARY KEY (film_id, user_id),
	CONSTRAINT likes_films_fk FOREIGN KEY (film_id) REFERENCES films(id),
	CONSTRAINT likes_users_fk FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS film_genre (
	film_id INTEGER,
	genre_id INTEGER,
	CONSTRAINT film_genre_films_fk FOREIGN KEY (film_id) REFERENCES films(id),
	CONSTRAINT film_genre_genres_fk FOREIGN KEY (genre_id) REFERENCES genres(id)
);