CREATE TABLE IF NOT EXISTS genres (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS directors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(100) NOT NULL,
	login VARCHAR(100) NOT NULL,
	name VARCHAR(100) NULL,
	birthday DATE,
	CONSTRAINT users_email_unique UNIQUE (email),
	CONSTRAINT users_login_unique UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS films (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(200),
	release_date DATE,
	duration INTEGER,
	mpa_id INTEGER,
	CONSTRAINT films_mpa_fk FOREIGN KEY (mpa_id) REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS friends (
	user_id INTEGER,
	friend_id INTEGER,
	status BOOLEAN,
	CONSTRAINT friends_pk PRIMARY KEY (user_id, friend_id),
	CONSTRAINT friends_users_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	CONSTRAINT friends_users_friend_fk FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (
	film_id INTEGER,
	user_id INTEGER,
	CONSTRAINT likes_pk PRIMARY KEY (film_id, user_id),
	CONSTRAINT likes_films_fk FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
	CONSTRAINT likes_users_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_genre (
	film_id INTEGER,
	genre_id INTEGER,
	CONSTRAINT film_genre_pk PRIMARY KEY (film_id, genre_id),
	CONSTRAINT film_genre_films_fk FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
	CONSTRAINT film_genre_genres_fk FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_director (
    film_id INTEGER,
    director_id INTEGER,
    CONSTRAINT film_director_pk PRIMARY KEY (film_id, director_id),
    CONSTRAINT film_director_film_fk FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    CONSTRAINT film_director_directors_fk FOREIGN KEY (director_id) REFERENCES directors(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR NOT NULL,
    is_positive BOOLEAN,
    user_id INTEGER,
    film_id INTEGER,
    useful INTEGER DEFAULT 0,
    CONSTRAINT reviews_users_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT reviews_films_fk FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    CONSTRAINT user_id_film_id_unique UNIQUE (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS reviews_likes (
	reviews_id INTEGER,
	user_id INTEGER,
	CONSTRAINT reviews_likes_pk PRIMARY KEY (reviews_id, user_id),
	CONSTRAINT reviews_likes_reviews_fk FOREIGN KEY (reviews_id) REFERENCES reviews(id) ON DELETE CASCADE,
	CONSTRAINT reviews_likes_users_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews_dislikes (
	reviews_id INTEGER,
	user_id INTEGER,
	CONSTRAINT reviews_dislikes_pk PRIMARY KEY (reviews_id, user_id),
	CONSTRAINT reviews_dislikes_reviews_fk FOREIGN KEY (reviews_id) REFERENCES reviews(id) ON DELETE CASCADE,
	CONSTRAINT reviews_dislikes_users_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);